# Site wide configuration

title: "Yuqian(Iris) Zhanfu"


description: ""
logo: logo.jpg# 120x120 px default image used for Twitter summary card
teaser: logo.jpg# 400x250 px default teaser image used in image archive grid
locale: en
# url: "https://yuqianz93320.github.io/yuqian93320.github.io"
#url: "https://yuqianz93320.github.io/yuqian93320.github.io"
feed:
  path: atom.xml

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
kramdown:
  toc_levels: 1..2
highlighter: rouge
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed


# Site owner
owner: 
  name: "Yuqian(Iris) Zhanfu"
  email: zhanfuyuqian@gmail.com
  twitter: 
  google: 
    ad-client:
    ad-slot:
  bio:
  avatar: avatar.jpg # 160x160 px image for author byline
  disqus-shortname:

defaults:
  # _posts
  - scope:
      path: "Portfolio"
      type: posts
    values:
      layout: article
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: true



include:
  - .htaccess
   ["_pages"]
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
